# Generated by Django 6.0 on 2025-12-30 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_source', models.CharField(default='PUBLIC_API', max_length=50)),
                ('sync_type', models.CharField(choices=[('MANUAL', '수동 요청'), ('BATCH', '자동 요청')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', '동기화 진행 중'), ('SUCCESS', '전체 성공'), ('PARTIAL', '일부 성공'), ('FAIL', '전체 실패')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=20, null=True)),
                ('result_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('request_rows', models.IntegerField(blank=True, null=True)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('insert_count', models.IntegerField(default=0)),
                ('update_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('triggered_by', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '축제 데이터 동기화 로그',
                'verbose_name_plural': '축제 데이터 동기화 로그 목록',
                'db_table': 'festival_sync_log',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='FestivalPublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_source', models.CharField(default='PUBLIC_API', max_length=50)),
                ('external_id', models.CharField(max_length=50)),
                ('main_title', models.CharField(blank=True, max_length=300, null=True)),
                ('gugun_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('place', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('main_place', models.CharField(blank=True, max_length=100, null=True)),
                ('addr1', models.CharField(blank=True, max_length=200, null=True)),
                ('addr2', models.CharField(blank=True, max_length=200, null=True)),
                ('cntct_tel', models.CharField(blank=True, max_length=200, null=True)),
                ('homepage_url', models.CharField(blank=True, max_length=200, null=True)),
                ('trfc_info', models.CharField(blank=True, max_length=500, null=True)),
                ('usage_day', models.CharField(blank=True, max_length=500, null=True)),
                ('usage_day_week_and_time', models.CharField(blank=True, max_length=500, null=True)),
                ('usage_amount', models.CharField(blank=True, max_length=500, null=True)),
                ('main_img_normal', models.CharField(blank=True, max_length=500, null=True)),
                ('main_img_thumb', models.CharField(blank=True, max_length=500, null=True)),
                ('item_contents', models.TextField(blank=True, null=True)),
                ('middle_size_rm1', models.CharField(blank=True, max_length=500, null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetched_sync', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_rows', to='festival.festivalsynclog')),
            ],
            options={
                'verbose_name': '축제 데이터 원본',
                'verbose_name_plural': '축제 데이터 원본 목록',
                'db_table': 'festival_public',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('external_source', 'external_id'), name='uq_public_source_id')],
            },
        ),
        migrations.CreateModel(
            name='FestivalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_source', models.CharField(default='PUBLIC_API', max_length=50)),
                ('external_id', models.CharField(max_length=50)),
                ('main_title', models.CharField(blank=True, max_length=300, null=True)),
                ('gugun_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('place', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('main_place', models.CharField(blank=True, max_length=100, null=True)),
                ('addr1', models.CharField(blank=True, max_length=200, null=True)),
                ('addr2', models.CharField(blank=True, max_length=200, null=True)),
                ('cntct_tel', models.CharField(blank=True, max_length=200, null=True)),
                ('homepage_url', models.CharField(blank=True, max_length=200, null=True)),
                ('trfc_info', models.CharField(blank=True, max_length=500, null=True)),
                ('usage_day', models.CharField(blank=True, max_length=500, null=True)),
                ('usage_day_week_and_time', models.CharField(blank=True, max_length=500, null=True)),
                ('usage_amount', models.CharField(blank=True, max_length=500, null=True)),
                ('main_img_normal', models.CharField(blank=True, max_length=500, null=True)),
                ('main_img_thumb', models.CharField(blank=True, max_length=500, null=True)),
                ('item_contents', models.TextField(blank=True, null=True)),
                ('middle_size_rm1', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_precision', models.CharField(choices=[('EXACT', '특정일'), ('RANGE_MONTH', '월 범위'), ('RANGE_YEAR', '연 범위'), ('TBD', '추후 공지'), ('ALWAYS', '상시'), ('UNKNOWN', '알 수 없음')], default='UNKNOWN', max_length=20)),
                ('extra_schedule_note', models.CharField(blank=True, max_length=500, null=True)),
                ('time_info_raw', models.CharField(blank=True, max_length=500, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edited_fields', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_synced_sync', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_rows', to='festival.festivalsynclog')),
            ],
            options={
                'verbose_name': '축제 데이터 운영용',
                'verbose_name_plural': '축제 데이터 운영용 목록',
                'db_table': 'festival_admin',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('external_source', 'external_id'), name='uq_admin_source_id')],
            },
        ),
    ]
