# Generated by Django 6.0 on 2025-12-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FestivalAdmin",
            new_name="Festival",
        ),
        migrations.RenameModel(
            old_name="FestivalPublic",
            new_name="FestivalRaw",
        ),
    ]
