# Generated by Django 6.0 on 2025-12-31 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0002_rename_festivaladmin_festival_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="festival",
            table="festival",
        ),
        migrations.AlterModelTable(
            name="festivalraw",
            table="festival_raw",
        ),
    ]
