# Generated by Django 6.0 on 2025-12-31 02:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0003_alter_festival_table_alter_festivalraw_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="FestivalI18n",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("kr", "한국어"),
                            ("en", "영어"),
                            ("jp", "일본어"),
                            ("cn", "중국어"),
                        ],
                        default="kr",
                        max_length=2,
                    ),
                ),
                ("main_title", models.CharField(blank=True, max_length=300, null=True)),
                ("place", models.CharField(blank=True, max_length=300, null=True)),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=300, null=True)),
                ("main_place", models.CharField(blank=True, max_length=100, null=True)),
                ("addr1", models.CharField(blank=True, max_length=200, null=True)),
                ("addr2", models.CharField(blank=True, max_length=200, null=True)),
                ("cntct_tel", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "homepage_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("trfc_info", models.CharField(blank=True, max_length=500, null=True)),
                ("usage_day", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "usage_day_week_and_time",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "usage_amount",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("item_contents", models.TextField(blank=True, null=True)),
                (
                    "middle_size_rm1",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "payload_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "축제 다국어(운영)",
                "verbose_name_plural": "축제 다국어(운영) 목록",
                "db_table": "festival_i18n",
                "ordering": ("festival_id", "lang"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="festival",
            name="uq_admin_source_id",
        ),
        migrations.RemoveConstraint(
            model_name="festivalraw",
            name="uq_public_source_id",
        ),
        migrations.AddField(
            model_name="festivalraw",
            name="lang",
            field=models.CharField(
                choices=[
                    ("kr", "한국어"),
                    ("en", "영어"),
                    ("jp", "일본어"),
                    ("cn", "중국어"),
                ],
                default="kr",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="festivalraw",
            name="last_synced_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="festivalraw",
            name="payload",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="festival",
            name="last_synced_sync",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="festival_rows",
                to="festival.festivalsynclog",
            ),
        ),
        migrations.AlterField(
            model_name="festivalraw",
            name="fetched_sync",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raw_rows",
                to="festival.festivalsynclog",
            ),
        ),
        migrations.AddIndex(
            model_name="festival",
            index=models.Index(
                fields=["external_source", "external_id"],
                name="festival_externa_49e562_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="festival",
            index=models.Index(fields=["gugun_nm"], name="festival_gugun_n_6a37e3_idx"),
        ),
        migrations.AddIndex(
            model_name="festival",
            index=models.Index(
                fields=["is_visible", "is_deleted"], name="festival_is_visi_21d8e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="festivalraw",
            index=models.Index(
                fields=["external_source", "external_id"],
                name="festival_ra_externa_d616f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="festivalraw",
            index=models.Index(fields=["lang"], name="festival_ra_lang_771baa_idx"),
        ),
        migrations.AddIndex(
            model_name="festivalraw",
            index=models.Index(
                fields=["updated_at"], name="festival_ra_updated_e9f839_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="festival",
            constraint=models.UniqueConstraint(
                fields=("external_source", "external_id"), name="uq_festival_source_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="festivalraw",
            constraint=models.UniqueConstraint(
                fields=("external_source", "external_id", "lang"),
                name="uq_festival_raw_source_id_lang",
            ),
        ),
        migrations.AddField(
            model_name="festivali18n",
            name="festival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="i18n",
                to="festival.festival",
            ),
        ),
        migrations.AddField(
            model_name="festivali18n",
            name="last_synced_sync",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="festival_i18n_rows",
                to="festival.festivalsynclog",
            ),
        ),
        migrations.RemoveField(
            model_name="festival",
            name="addr1",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="addr2",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="cntct_tel",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="homepage_url",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="item_contents",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="main_place",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="main_title",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="middle_size_rm1",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="place",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="title",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="trfc_info",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="usage_amount",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="usage_day",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="usage_day_week_and_time",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="addr1",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="addr2",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="cntct_tel",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="gugun_nm",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="homepage_url",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="item_contents",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="lng",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="main_img_normal",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="main_img_thumb",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="main_place",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="main_title",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="middle_size_rm1",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="place",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="title",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="trfc_info",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="usage_amount",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="usage_day",
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="usage_day_week_and_time",
        ),
        migrations.AddIndex(
            model_name="festivali18n",
            index=models.Index(fields=["lang"], name="festival_i1_lang_c1b704_idx"),
        ),
        migrations.AddIndex(
            model_name="festivali18n",
            index=models.Index(
                fields=["festival", "lang"], name="festival_i1_festiva_ba53ac_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="festivali18n",
            constraint=models.UniqueConstraint(
                fields=("festival", "lang"), name="uq_festival_i18n_festival_lang"
            ),
        ),
    ]
