# Generated by Django 6.0 on 2025-12-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0004_festivali18n_remove_festival_uq_admin_source_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="festivali18n",
            name="festival_i1_lang_c1b704_idx",
        ),
        migrations.RemoveIndex(
            model_name="festivali18n",
            name="festival_i1_festiva_ba53ac_idx",
        ),
        migrations.RemoveConstraint(
            model_name="festivali18n",
            name="uq_festival_i18n_festival_lang",
        ),
        migrations.RemoveConstraint(
            model_name="festivalraw",
            name="uq_festival_raw_source_id_lang",
        ),
        migrations.RemoveIndex(
            model_name="festivalraw",
            name="festival_ra_lang_771baa_idx",
        ),
        migrations.AddField(
            model_name="festival",
            name="addr1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="addr2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="cntct_tel",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="homepage_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="item_contents",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="main_place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="main_title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="middle_size_rm1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="place",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="trfc_info",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="usage_amount",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="usage_day",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="usage_day_week_and_time",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="festivalsynclog",
            name="raw_file_checksum",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="festivalsynclog",
            name="raw_file_path",
            field=models.CharField(
                blank=True,
                help_text="원본 공공데이터 JSON 파일 경로(static 하위 상대경로)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="festivalsynclog",
            name="raw_file_size",
            field=models.BigIntegerField(
                blank=True, help_text="원본 JSON 파일 크기(bytes)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="festivalsynclog",
            name="sync_type",
            field=models.CharField(
                choices=[("MANUAL", "수동 요청"), ("BATCH", "자동 요청")],
                default="BATCH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="festivalsynclog",
            name="triggered_by",
            field=models.CharField(default="system", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="festivalraw",
            constraint=models.UniqueConstraint(
                fields=("external_source", "external_id"),
                name="uq_festival_raw_source_id",
            ),
        ),
        migrations.RemoveField(
            model_name="festivalraw",
            name="lang",
        ),
        migrations.DeleteModel(
            name="FestivalI18n",
        ),
    ]
