# Generated by Django 6.0 on 2025-12-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0005_remove_festivali18n_festival_i1_lang_c1b704_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="date_precision",
            field=models.CharField(
                choices=[
                    ("EXACT", "특정일"),
                    ("RANGE", "시작, 끝 날짜"),
                    ("RANGE_MONTH", "월 범위"),
                    ("RANGE_YEAR", "연 범위"),
                    ("TBD", "추후 공지"),
                    ("ALWAYS", "상시"),
                    ("UNKNOWN", "알 수 없음"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
