# Generated by Django 6.0 on 2025-12-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0006_alter_festival_date_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='payload_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='extra_schedule_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
