# Generated by Django 6.0 on 2025-12-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_festival_payload_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalsynclog',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festivalsynclog',
            name='apply_error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festivalsynclog',
            name='apply_insert_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festivalsynclog',
            name='apply_skip_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='festivalsynclog',
            name='apply_status',
            field=models.CharField(blank=True, choices=[('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='festivalsynclog',
            name='apply_update_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
