# Generated by Django 6.0 on 2026-01-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0008_festivalsynclog_applied_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="festivalsynclog",
            options={
                "ordering": ("-started_at",),
                "verbose_name": "축제 데이터 동기화 로그",
                "verbose_name_plural": "축제 데이터 동기화 로그",
            },
        ),
    ]
