# Generated by Django 6.0 on 2026-01-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0009_alter_festivalsynclog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalraw",
            name="main_title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
