# Generated by Django 6.0 on 2026-01-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0010_festivalraw_main_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="festival",
            old_name="main_place",
            new_name="main_place_raw",
        ),
        migrations.RenameField(
            model_name="festival",
            old_name="main_title",
            new_name="main_title_raw",
        ),
        migrations.RenameField(
            model_name="festival",
            old_name="place",
            new_name="place_raw",
        ),
        migrations.RenameField(
            model_name="festival",
            old_name="title",
            new_name="title_raw",
        ),
        migrations.AddField(
            model_name="festival",
            name="place_display",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="festival",
            name="title_display",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="festival",
            name="date_precision",
            field=models.CharField(
                choices=[
                    ("EXACT", "EXACT"),
                    ("RANGE", "RANGE"),
                    ("RANGE_MONTH", "RANGE_MONTH"),
                    ("RANGE_YEAR", "RANGE_YEAR"),
                    ("TBD", "TBD"),
                    ("ALWAYS", "ALWAYS"),
                    ("UNKNOWN", "UNKNOWN"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
    ]
