# Generated by Django 6.0 on 2026-01-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0011_rename_main_place_festival_main_place_raw_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="festival",
            old_name="title_display",
            new_name="main_title_display",
        ),
        migrations.RemoveField(
            model_name="festival",
            name="title_raw",
        ),
    ]
