# Generated by Django 6.0 on 2026-01-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0012_rename_title_display_festival_main_title_display_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="title",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
