# Generated by Django 6.0 on 2026-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0013_festival_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festival",
            name="item_contents",
            field=models.TextField(),
        ),
    ]
