# Generated by Django 6.0 on 2026-01-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0014_alter_festival_item_contents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="festival",
            name="time_info_raw",
        ),
        migrations.AddField(
            model_name="festival",
            name="note_months",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="festival",
            name="item_contents",
            field=models.TextField(blank=True, null=True),
        ),
    ]
