# Generated by Django 6.0 on 2026-01-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "festival",
            "0015_remove_festival_time_info_raw_festival_note_months_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
