# Generated by Django 6.0 on 2026-01-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("festival", "0016_festival_view_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="festival",
            old_name="middle_size_rm1",
            new_name="facilities",
        ),
    ]
